project:
  type: website
  output-dir: docs

website:
  title: "Sumaila Kwame Iddrisu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

